### ISSUE TITLE
运行 qq.py 之后报错

### ISSUE THREAD

**Issue by yEs1do** [yingshaoxo/Telegram-with-QQ#1]
[root@vultr Telegram-with-QQ]# python3.6 qq.py
Traceback (most recent call last):
  File "qq.py", line 105, in <module>
    from qqbot import QQBotSlot as qqbs, RunBot
ModuleNotFoundError: No module named 'qqbot'

**Comment by yingshaoxo** [comment]
`pip3 install pyTelegramBotAPI`

**Comment by yingshaoxo** [comment]
https://github.com/pandolia/qqbot

**Comment by yEs1do** [comment]
知道了，我安装的是 3.6 版本，你的代码里应该用的都是 python3 而不是python3.6

**Comment by yingshaoxo** [comment]
大概是3.5吧，下次我做开发把版本号带上去，谢谢反馈
