### ISSUE TITLE
转发消息失败

### ISSUE THREAD

**Issue by yEs1do** [yingshaoxo/Telegram-with-QQ#2]
两步均正常运行，qqbot 能够收到消息，但是 Telegram 的机器人不能获得消息，是不是需要改 chat_id？

**Comment by yingshaoxo** [comment]
可以改下试试，另外启动后master账号手动向telegram你的目标群发一个消息，应该会自动获取chat-id

**Comment by yingshaoxo** [comment]
还有，你的telebot必须是管理员

**Comment by yEs1do** [comment]
手动改的，自动获取多次无果，而且还是用的另一个 bot 获取的

**Comment by yingshaoxo** [comment]
没法转图片，我觉得就没意思，所以我最近几个月都没用，等以后有机会再跟新吧...

**Comment by yEs1do** [comment]
然而酷Q折腾失败，文档也没有多少。你这个可以加入多群组互连和回复功能吗？

**Comment by yEs1do** [comment]
@yEs1do 是时候学波 Python 自己搞了 😣

**Comment by yingshaoxo** [comment]
可以

**Comment by yEs1do** [comment]
怎么搞多群组和回复，指点一下

**Comment by yingshaoxo** [comment]
@yingshaoxo telegram邀我进群测试
